students =["Giovanna Fuller", "Pierre Baxter", "Maxim Walker", "Dale Fuller", 
"Keshawn Campbell", "Chaya Mills", "Alyson Grant", "Lindsay Glover", 
"Carson Mcbride", "Zechariah Pitts", "Davon Trujillo", "Annabel Villegas", 
"Johnathon Dickerson", "Alexa Mullins", "Lucas Ray", "Bailey Todd", 
"Brooks Ewing", "Malaki Campos", "Annabel Campbell", "Desmond Davis", 
"Max Blackburn", "Alivia Key", "Alvin Massey", "Marc Riddle", 
"Zachariah Bender", "Lea Velez", "Desmond Hines", "Amir Villegas", "Asia Floyd", 
"Ahmad Barajas", "Paige Vang", "Taylor Logan", "Ahmed Duran", "Brielle Manning", 
"Elianna Shepard", "Leon Murillo", "Camryn Bradley", "Henry Kemp", 
"Hazel Hancock", "Vivian Gallegos"]